channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - click=8.1.7
  - pip=23.2.1
  - pre-commit=3.5.0
  - python~=3.11.0
  - ruff=0.2.1

pip:
  - biopython==1.83
  - orfipy==0.0.4
  - tqdm
