channels:
  - nvidia
  - pytorch
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - biopython=1.83
  - click=8.1.7
  - diamond=2.1.9
  - mmseqs2=14.7e284
  - pandas=2.2.0
  - pip=23.2.1
  - pre-commit=3.5.0
  - pytest=8.2.2
  - python~=3.11.0
  - pytorch::pytorch=2.2.0
  - pytorch::pytorch-cuda=12.1
  - ruff=0.2.1
  - requests=2.31.0
  - scikit-learn=1.4.0
  - seqkit=2.7.0

  - pip:
    - orfipy==0.0.4
    - tqdm==4.66.2
    - git+https://github.com/facebookresearch/esm.git@v1.0.3#egg=fair-esm
